theme: jekyll-theme-tactile
title: Welcome to gjys2000's homepage!
description: This is a work in progress, at least for now! I plan on adding new things to this website as I learn more about GitHub.
