theme: jekyll-theme-tactile
title: Welcome to gjys2000's homepage!
description: This is a work in progress, at least for now! I plan on adding new things to this website as I learn more about GitHub. At the moment, I'm still in the process of enrolling in units - not too sure which ones to choose yet.
